version: "3.8"

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - database-volume:/var/lib/postgresql  # mount a volume for persistent storage
  pgadmin:
    image: dpage/pgadmin4:5.0  # Pin for no good reason
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
      - "443:443"


volumes:
  database-volume:
