from rabbitmq:latest

RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements-queues.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY src/lib /src/lib
COPY src/rabbit /src/rabbit
RUN rabbitmq-plugins enable rabbitmq_management
