version: "3.8"

services:
  queue-shack:
    build:
      context: .
      dockerfile: dockerfile.rabbitmq
    hostname: 'queue-shack'
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
      - "./rabbit-data:/var/lib/rabbitmq/mnesia/"